version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[transformers]]
name = "standardjs"